spring.profiles.active: prod

spring.config.import: file:env.properties
spring.messages.basename: messages/messages

riot.api-key: ${API_KEY_RIOT}

spring:
  shell:
    interactive:
      enabled: false
    command:
      stacktrace:
        enabled: false
      script:
        enabled : false
      history:
        enabled: false
      version:
        enabled: false

ssh:
  shell:
    user: ${SHELL_USER}
    password: ${SHELL_PASSWORD}
    host: ${SHELL_HOST}
    port: ${SHELL_PORT}
    host-key-file: ${java.io.tmpdir}/hostKey.ser
    commands:
      jmx:
        create: false
      script:
        create: false
      history:
        create: false
      postprocessors:
        create: false
      manage-sessions:
        create: false
      system:
        create: false
      stacktrace:
        create: false

logging:
  level:
    com.github.fonimus: info
